GET http://localhost:3001/todos

###

POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text": "Make a brand new task" 
}

###
DELETE http://localhost:3001/todo/delete/64c917bbb51098dc839e9cc0

###
GET http://localhost:3001/todo/complete/64c91785b51098dc839e9cbd